up

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -116,32 +116,33 @@ jobs:
           wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb
           sudo dpkg -i ${{ runner.temp }}/hugo.deb
 
-      - name: Checkout
+      - name: Checkout Repository
         uses: actions/checkout@v3
         with:
           ref: master
 
-      - name: Setup Pages
+      - name: Setup GitHub Pages
         id: pages
         uses: actions/configure-pages@v3
 
       - name: Get Theme
         run: git submodule update --init --recursive
 
-      - name: Update theme to Latest commit
+      - name: Update Theme to Latest Commit
         run: git submodule update --remote --merge
 
       - name: Build with Hugo
         run: |
           hugo --buildDrafts --gc --baseURL "${{ steps.pages.outputs.base_url || '/' }}"
 
-      - name: Debug Build Output
-        run: ls -lah ./public
+      - name: Debug: Check if Public Folder Exists
+        run: ls -lah ./public || echo "Public folder not found!"
 
-      - name: Upload artifact
+      - name: Upload GitHub Pages Artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./public
+          name: github-pages # Required for deploy-pages to find it
 
   deploy:
     environment:
